#!/bin/bash

#
#  Sample of helpers that can be used by application installers.
#  Alternately: just use a yaml editor
#

#  load helpers
source $CSAP_FOLDER/bin/csap-environment.sh

# option: specify folder as param; defaults to $(pwd)
build_auto_play_file

append_yaml_comment
append_yaml_comment "generated by my-app-install.sh"
append_yaml_comment

#
# append_yaml <indents> <value>
#
append_yaml 0 "environments:"
append_yaml 1 "active: test"

append_yaml 1 "hosts:"
append_yaml 2 "base-os: [ host-1, host-2, host3, host4 ]"
# or
append_yaml 3 "- auto-1"
append_yaml 3 "- auto-2"
append_yaml 3 "- auto-3"
append_yaml 3 "- auto-4"

