


---
#
# Sample: Creating a file, path is relative to csap-platfrom/definition
#
operator: create
target: scripts/hi.sh

content: |
  #!/bin/bash
  echo "hi"


---
#
#  Docker Repository
#
operator: create

target: resources/docker/common/configuration/daemon.json

exec-opts: ["native.cgroupdriver=systemd"]
  
registry-mirrors: ["http://docker.yourcompany.org"]
insecure-registries: [ "yourcompany-docker.yourcompany.org", "docker.yourcompany.org" ]
storage-driver: "overlay2"
data-root: "/var/lib/docker"
hosts: [ "unix:///var/run/docker.sock" ]
log-driver: "json-file"
log-opts: 
  max-size: "44m"
  max-file: "1"
  






---
#
# Core csap settings: yourcompany yourtown Security(LDAP)
#
operator: create
target: application-company.yml

#
# Global settings for applications - test
#

spring: 
  mail: 
    host: "${mailServer:myrelay.yourcompany.com}"
    port: "${mailPort:25}"

csap.security: 
    rest-api-filter.token: "k16ljSCT5UnF8o1fCyshcD3+VZtrWm2c"
    provider:
      type: ldap
      url: ldap://ldap.davis.yourcompany.lab:389
      directory-dn: search:uid={0}
      search-user: ou=People,dc=flexnet,dc=net
      search-groups: ou=Groups,dc=flexnet,dc=net
            
#      type: memory
#      memory-users:
#      - admin,password,AUTHENTICATED,dummy1,dummy2
#      - user,password,AUTHENTICATED,dummy3,dummy4
      
csap-core:

  kubernetes: 
    enabled: true

  docker: 
    enabled: true
    

#
# health and data services
#
csap-events: 

  health-monitoring: 
    appIds:
      - xxx
    lifes:
      - dev





---
#
# Optional: yourcompany yourtown Artifactory Repository
#
operator: create
target: resources/settings.xml

content: |
  <?xml version="1.0" encoding="UTF-8"?>
  <settings
    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd"
    xmlns="http://maven.apache.org/SETTINGS/1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
    <localRepository>${CSAP_FOLDER}/maven-repository</localRepository>
  
    <servers>
  
      <server>
        <id>yourcompany-artifactory-community</id>
        <username>pnightingale</username>
        <password>update-me</password>
      </server>
      <server>
        <id>csap-release-repo</id>
        <username>pnightingale</username>
        <password>update-me</password>
      </server>
  
      <server>
        <id>csap-snapshot-repo</id>
        <username>pnightingale</username>
        <password>update-me</password>
      </server>
  
    </servers>
    <mirrors>
      <mirror>
        <id>yourcompany-artifactory-community</id>
        <mirrorOf>*</mirrorOf>
        <url>http://my-server-01.yourcompany.org:8081/artifactory/maven</url>
      </mirror>
    </mirrors>
    <profiles>
      <profile>
        <id>yourcompany-artifactory-community</id>
  
        <properties>
          <csapReleaseUrl>http://my-server-01.yourcompany.org:8081/artifactory/csap-release</csapReleaseUrl>
          <csapSnapUrl>http://my-server-01.yourcompany.org:8081/artifactory/csap-snapshots</csapSnapUrl>
          <artifactoryCnameFqdn>yourcompany-artifactory-community.yourcompany.org</artifactoryCnameFqdn>
        </properties>
  
        <repositories>
          <repository>
            <snapshots>
              <enabled>true</enabled>
              <updatePolicy>always</updatePolicy>
            </snapshots>
            <id>yourcompany-artifactory-community</id>
            <name>central</name>
            <url>http://central</url>
            <releases>
              <enabled>true</enabled>
              <updatePolicy>always</updatePolicy>
            </releases>
          </repository>
        </repositories>
        <pluginRepositories>
          <pluginRepository>
            <id>central</id>
            <url>http://central</url>
            <snapshots>
              <enabled>true</enabled>
            </snapshots>
            <releases>
              <enabled>true</enabled>
            </releases>
          </pluginRepository>
        </pluginRepositories>
      </profile>
      
      
      <!-- USED in java spring boot build manifest -->
      <profile>
        <id>jenkins-node-name-default</id>
        <activation>
          <property>
            <name>!env.NODE_NAME</name>
          </property>
        </activation>
        <properties>
          <build.node>built-on-unofficial-host</build.node>
        </properties>
      </profile>
  
      <profile>
        <id>jenkins-node-name-from-env</id>
        <activation>
          <property>
            <name>env.NODE_NAME</name>
          </property>
        </activation>
        <properties>
          <build.node>${env.NODE_NAME}</build.node>
        </properties>
      </profile>
      
    </profiles>
    <activeProfiles>
      <activeProfile>yourcompany-artifactory-community</activeProfile>
    </activeProfiles>
  </settings>






