#
# https://github.com/coreos/prometheus-operator/tree/master/example/user-guides/getting-started
#


apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app-pods
  template:
    metadata:
      labels:
        app: example-app-pods
    spec:
      containers:
      - name: example-app-container
        image: fabxc/instrumented_app
        ports:
        - name: web
          containerPort: 8080

          
---
kind: Service
apiVersion: v1
metadata:
  name: example-app-service
  labels:
    app: example-app-service
spec:
  selector:
    app: example-app-pods
  ports:
  - name: web
    port: 8080

---
# https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#servicemonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app-monitor
  labels:
    team: example-monitors
spec:
  selector:
    matchLabels:
      app: example-app-service
  endpoints:
  - port: web
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-promethius-account

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: demo-promethius
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: demo-promethius
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: demo-promethius
subjects:
- kind: ServiceAccount
  name: demo-promethius-account
  namespace: default

---

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: example-app-promethius
spec:
  serviceAccountName: demo-promethius-account
  serviceMonitorSelector:
    matchLabels:
      team: example-monitors
  resources:
    requests:
      memory: 400Mi
      
---

apiVersion: v1
kind: Service
metadata:
  name: example-app-promethius-service
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: example-app-promethius