#
# Notes:
#   - https://kubernetes.io/docs/concepts/storage/volumes/#vspherevolume
#   - https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/policy-based-mgmt.html
#
# Setup: 
# - kubernete cloud provider configuration for vsphere: https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/
#

apiVersion: v1
kind: PersistentVolume

metadata:
  name: "test-vsphere-static-pv"
  labels:
    disk: "test-vsphere-static-disk"
  
spec: 
  
  capacity:
    storage: 10Mi
    
  accessModes:
    - ReadWriteOnce
    
  persistentVolumeReclaimPolicy: Retain
  
  vsphereVolume:
    volumePath: "[CSAP_DS1_NFS] demo-folder/demo-disk.vmdk"
    fsType: ext4
    
---

kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: test-vsphere-static-pvc
  
spec:
  # must be explictly blanked out or default class will be used
  storageClassName: ""
  
  selector:
      matchLabels:
        disk: "test-vsphere-static-disk"
  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---



kind: Deployment

apiVersion: apps/v1

metadata:
  name: nginx-with-vsphere-static-pv
  namespace: default
  labels:
    csap-deploy-sample: nginx-static-pv-id
    
spec:
  selector:
    matchLabels:
      csap-deploy-sample: nginx-static-pv-id
      
  replicas: 1
  
  template:
  
    metadata:
      name: "nginx-demo-pod-template"
      labels:
        csap-deploy-sample: nginx-static-pv-id
        matchForDemoService: nginx-static-target

      annotations:     
        "sample-1": "value-1" 
        
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: nginx-container
        image: nginx:latest
        
        ports:
        - containerPort: 80
        
        command:
          - "/bin/sh"
          
        args:
          - "-c"
          - "
          htmlFolder=/usr/share/nginx/html;
          ls -al $htmlFolder ; NOW=$(date +'%h-%d-%I-%M-%S'); 
          
          touch $htmlFolder/SUCCESS-$NOW; 
          echo hi >> $htmlFolder/SUCCESS-$NOW ; 
          
          echo creating $htmlFolder/index.html;
          echo hi there from a nginx-with-vsphere-static-pv at $NOW >> $htmlFolder/index.html; 
          
          nginx -g 'daemon off;'
          "
          
        readinessProbe:
          initialDelaySeconds: 3
          timeoutSeconds: 3
          periodSeconds: 3
          failureThreshold: 1
          httpGet:
            path: /
            port: 80
            
        livenessProbe:
          initialDelaySeconds: 3
          timeoutSeconds: 3
          periodSeconds: 3
          failureThreshold: 1
          httpGet:
            path: /
            port: 80
          
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: my-vsphere-pvc
          
      volumes:
      - name: my-vsphere-pvc
        persistentVolumeClaim: 
          claimName: test-vsphere-static-pvc

        
---

kind: Service
apiVersion: v1
metadata:
  name: nginx-with-vsphere-static-pv-service
  namespace: default
spec:
  type: NodePort # defaults to clusterip
  selector:
    matchForDemoService: nginx-static-target
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    
