#
# ref https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/
#


kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer


---

#
# raw block device: 
#   - use infra provider (eg. vcenter ui)
#   - govc datastore.disk.create -ds CSAP_DS1_NFS  -size 10M peter.vmdk
#

apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-local-pv
spec:
  capacity:
    storage: 10Mi # 100Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /opt/csap/local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - example-node
          
---

kind: Pod
apiVersion: v1
metadata:
  name: example-local-pod
spec:
  containers:
  - name: test-pod
    image: gcr.io/google_containers/busybox:1.32.0
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS ; ls -l ; sleep 500"
    volumeMounts:
      - name: my-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: my-pvc
      persistentVolumeClaim:
        claimName: example-local-pv
